### PR TITLE
[TD-4342]<fix>: go mod init bailongma/v2 then go build.

### PR DESCRIPTION
**Pull request by sangshuduo**

### CODE REVIEW

**Comment by zitsen** [comment]
Where is v2?

**Comment by sangshuduo** [comment]
@zitsen it's the way what go module v2 requires. please refer to 

https://yunuskilicdev.medium.com/managing-dependencies-with-go-modules-4a6111d641cc

 https://github.com/taosdata/Bailongma/pull/15#issuecomment-847492448

**Comment by zitsen** [comment]
```
server.go:38:2: package bailongma/v2/blm_prometheus/pkg/log is not in GOROOT (/home/huolinhe/.local/go/src/bailongma/v2/blm_prometheus/pkg/log)
server.go:19:2: package bailongma/v2/blm_prometheus/pkg/tdengine is not in GOROOT (/home/huolinhe/.local/go/src/bailongma/v2/blm_prometheus/pkg/tdengine)
server.go:20:2: package bailongma/v2/blm_prometheus/pkg/tdengine/write is not in GOROOT (/home/huolinhe/.local/go/src/bailongma/v2/blm_prometheus/pkg/tdengine/write)
```

**Comment by sangshuduo** [comment]
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (master)$ **git fetch origin pull/16/head:pr-16**  
remote: Enumerating objects: 11, done.  
remote: Counting objects: 100% (11/11), done.  
remote: Compressing objects: 100% (4/4), done.  
remote: Total 11 (delta 6), reused 11 (delta 6), pack-reused 0  
Unpacking objects: 100% (11/11), done.  
From https://github.com/taosdata/Bailongma  
\* \[new ref\]         refs/pull/16/head -> pr-16

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (master)$ **git co pr-16**  
Switched to branch 'pr-16'  
 

shuduo@ubuntu1804 ~/work/taosdata/Bailongma/blm\_telegraf (pr-16)$ **go version**  
go version go1.16.2 linux/amd64

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (pr-16)$ **go mod init bailongma/v2**  
go: creating new go.mod: module bailongma/v2  
go: to add module requirements and sums:  
       go mod tidy

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (pr-16)$ **go mod tidy**  
go: finding module for package github.com/prometheus/prometheus/prompb  
go: finding module for package github.com/golang/snappy  
go: finding module for package github.com/prometheus/common/model  
go: finding module for package github.com/gogo/protobuf/proto  
go: finding module for package github.com/taosdata/driver-go/taosSql  
go: finding module for package github.com/emirpasic/gods/sets/hashset  
go: found github.com/gogo/protobuf/proto in github.com/gogo/protobuf v1.3.2  
go: found github.com/golang/snappy in github.com/golang/snappy v0.0.3  
go: found github.com/prometheus/common/model in github.com/prometheus/common v0.25.0  
go: found github.com/prometheus/prometheus/prompb in github.com/prometheus/prometheus v2.5.0+incompatible  
go: found github.com/taosdata/driver-go/taosSql in github.com/taosdata/driver-go v0.0.0-20210521015739-8ce6d86558af  
go: found github.com/emirpasic/gods/sets/hashset in github.com/emirpasic/gods v1.12.0

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (pr-16)$ **cd blm\_prometheus/**

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma/blm\_prometheus (pr-16)$ **go build**  
  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma/blm\_prometheus (pr-16)$ **cd ../blm\_telegraf/**

  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma/blm\_telegraf (pr-16)$ **go build**

**Review by zitsen — APPROVED** [review]
LGTM

**Pull request merged**
