### PR TITLE
Add Prometheus remote_read from TDengine and tidy code modules

### PR DESCRIPTION
**Pull request by HendSame**
#9 

Add Prometheus remote_read from TDengine and tidy code modules

And I have did the test with my local's prometheus. It worked well.

### CODE REVIEW

**Review by sangshuduo — COMMENTED** [review]
1. I remember the go.mod need with fixed commit of the prometheus due to its API continuously change. May I know if all the prometheus can work with Bailongma now?
2. regarding remote_read url endpoint's name, my opinion is maybe 'send' is better than 'read' since the remote_write use 'receive'.

**Comment by HendSame** [comment]
> 1. I remember the go.mod need with fixed commit of the prometheus due to its API continuously change. May I know if all the prometheus can work with Bailongma now?

## Firstly：
My go.mod use that commit of the prometheus : 
```
go 1.16

require (
	github.com/gogo/protobuf v1.3.2
	github.com/golang/snappy v0.0.3
	github.com/prometheus/common v0.23.0
	github.com/prometheus/prometheus v2.5.0+incompatible
	github.com/taosdata/driver-go v0.0.0-20210427081935-7a26c432f8b4
)
```
It can work with Bailongma.
1、Write metric to TDengine well. 
write 

2、Read metric from TDengine well.
read 
read_log 

## Secondly: 
These are the commits of  Prometheus  about the remote_read and remote_write from 2017 to now.
commits

1、remote_write API

#### The fist version:
```
type WriteRequest struct {
	type WriteRequest struct {
	Timeseries []*TimeSeries `protobuf:"bytes,1,rep,name=timeseries" json:"timeseries,omitempty"`
}
type TimeSeries struct {
	Labels  []*Label  `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
	Samples []*Sample `protobuf:"bytes,2,rep,name=samples" json:"samples,omitempty"`
}
type Label struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}
type Sample struct {
	Value     float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp int64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

```

#### The lastest version:
```

type WriteRequest struct {
	Timeseries           []TimeSeries     `protobuf:"bytes,1,rep,name=timeseries,proto3" json:"timeseries"`
	Metadata             []MetricMetadata `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}
type TimeSeries struct {
	Labels               []Label  `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels"`
	Samples              []Sample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
type Label struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
type Sample struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```
So the data protocol is forward compatible.

2、remote_read API

#### The fist version:
```

type ReadRequest struct {
	Queries []*Query `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}
type Query struct {
	StartTimestampMs int64           `protobuf:"varint,1,opt,name=start_timestamp_ms,json=startTimestampMs,proto3" json:"start_timestamp_ms,omitempty"`
	EndTimestampMs   int64           `protobuf:"varint,2,opt,name=end_timestamp_ms,json=endTimestampMs,proto3" json:"end_timestamp_ms,omitempty"`
	Matchers         []*LabelMatcher `protobuf:"bytes,3,rep,name=matchers" json:"matchers,omitempty"`
}
type LabelMatcher struct {
	Type  LabelMatcher_Type `protobuf:"varint,1,opt,name=type,proto3,enum=prometheus.LabelMatcher_Type" json:"type,omitempty"`
	Name  string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}
const (
	LabelMatcher_EQ  LabelMatcher_Type = 0
	LabelMatcher_NEQ LabelMatcher_Type = 1
	LabelMatcher_RE  LabelMatcher_Type = 2
	LabelMatcher_NRE LabelMatcher_Type = 3
)
```

#### The lastest version:

```

type ReadRequest struct {
	Queries []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// accepted_response_types allows negotiating the content type of the response.
	//
	// Response types are taken from the list in the FIFO order. If no response type in `accepted_response_types` is
	// implemented by server, error is returned.
	// For request that do not contain `accepted_response_types` field the SAMPLES response type will be used.
	AcceptedResponseTypes []ReadRequest_ResponseType `protobuf:"varint,2,rep,packed,name=accepted_response_types,json=acceptedResponseTypes,proto3,enum=prometheus.ReadRequest_ResponseType" json:"accepted_response_types,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                   `json:"-"`
	XXX_unrecognized      []byte                     `json:"-"`
	XXX_sizecache         int32                      `json:"-"`
}
type Query struct {
	StartTimestampMs     int64           `protobuf:"varint,1,opt,name=start_timestamp_ms,json=startTimestampMs,proto3" json:"start_timestamp_ms,omitempty"`
	EndTimestampMs       int64           `protobuf:"varint,2,opt,name=end_timestamp_ms,json=endTimestampMs,proto3" json:"end_timestamp_ms,omitempty"`
	Matchers             []*LabelMatcher `protobuf:"bytes,3,rep,name=matchers,proto3" json:"matchers,omitempty"`
	Hints                *ReadHints      `protobuf:"bytes,4,opt,name=hints,proto3" json:"hints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}
type LabelMatcher struct {
	Type                 LabelMatcher_Type `protobuf:"varint,1,opt,name=type,proto3,enum=prometheus.LabelMatcher_Type" json:"type,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}
const (
	LabelMatcher_EQ  LabelMatcher_Type = 0
	LabelMatcher_NEQ LabelMatcher_Type = 1
	LabelMatcher_RE  LabelMatcher_Type = 2
	LabelMatcher_NRE LabelMatcher_Type = 3
)
```
So the data protocol is forward compatible too.


> 2. regarding remote_read url endpoint's name, my opinion is maybe 'send' is better than 'read' since the remote_write use 'receive'.

Maybe it's best use 'pull' that reference from [prometheus.io](https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/#remote-read):
```
Write - receive samples pushed by Prometheus
Read - pull samples from Prometheus
```

**Review by sangshuduo — CHANGES_REQUESTED** [review]
please change remote_read url endpoint to 'pull' as prometheus official reference asks.

**Comment by sangshuduo** [comment]
@HendSame thanks for your contribution. Please change the endpoint's name.

**Comment by HendSame** [comment]
@sangshuduo 
Fix.

**Review by sangshuduo — APPROVED** [review]
LGTM

**Comment by sangshuduo** [comment]
@HendSame interested what version of golang you are using? could you please try to build #16 to see if it work with your version? 

I encounter build issue as below, until fixed with solution #16 

\--

shuduo@ubuntu1804 ~/work/taosdata/Bailongma (master)$ go mod init bailongma/v2  
go: creating new go.mod: module bailongma/v2  
go: to add module requirements and sums:  
       go mod tidy  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (master)$ go mod tidy  
go: finding module for package github.com/gogo/protobuf/proto  
go: finding module for package github.com/golang/snappy  
go: finding module for package github.com/prometheus/common/model  
go: finding module for package github.com/prometheus/prometheus/prompb  
go: finding module for package github.com/taosdata/driver-go/taosSql  
go: finding module for package github.com/emirpasic/gods/sets/hashset  
go: found github.com/gogo/protobuf/proto in github.com/gogo/protobuf v1.3.2  
go: found github.com/golang/snappy in github.com/golang/snappy v0.0.3  
go: found github.com/prometheus/common/model in github.com/prometheus/common v0.25.0  
go: found github.com/prometheus/prometheus/prompb in github.com/prometheus/prometheus v2.5.0+incompatible  
go: found github.com/taosdata/driver-go/taosSql in github.com/taosdata/driver-go v0.0.0-20210521015739-8ce6d86558af  
go: found github.com/emirpasic/gods/sets/hashset in github.com/emirpasic/gods v1.12.0  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma (master)$ cd blm\_prometheus/  
shuduo@ubuntu1804 ~/work/taosdata/Bailongma/blm\_prometheus (master)$ go build  
server.go:38:2: package blm\_prometheus/pkg/log is not in GOROOT (/usr/lib/go-1.16/src/blm\_prometheus/pkg/log)  
server.go:19:2: package blm\_prometheus/pkg/tdengine is not in GOROOT (/usr/lib/go-1.16/src/blm\_prometheus/pkg/tdengine)  
server.go:20:2: package blm\_prometheus/pkg/tdengine/write is not in GOROOT (/usr/lib/go-1.16/src/blm\_prometheus/pkg/tdengine/write)

**Comment by HendSame** [comment]
@sangshuduo  Sorry it took so long to reply.
I was run `go mod init ` in the `/Bailongma/blm_prometheus`. So it was work well.
Glad that someone found the problem.

**Comment by sangshuduo** [comment]
@HendSame thank you again.

**Pull request merged**
